export const datatabless = [
    {
        id: 1,
        commodityname:'cahsew',
        country:'edinburgh',
        price:'$320,800',
        origin:'delta',
        specification:'improved quality',
        description:'full tonne',
        status:'available',
        view:'view',
        delete:'delete',
        },
    {
        id: 2,
        commodityname:'groundnut',
        country:'london',
        price:'$420,800',
        origin:'delta',
        specification:'improved quality',
        description:'full tonne',
        status:'available',
        view:'view',
        delete:'delete',
    },
    {
        id: 3,
        commodityname:'paddy rice',
        country:'mali',
        price:'$520,800',
        origin:'delta',
        specification:'improved quality',
        description:'full tonne',
        status:'out of stock',
        view:'view',
        delete:'delete',
    },
    {
        id: 4,
        commodityname:'beans',
        country:'ghana',
        price:'$620,800',
        origin:'sapele',
        specification:'improved quality',
        description:'half tonne',
        status:'unavailable',
        view:'view',
        delete:'delete',
    },
    {
        id: 5,
        commodityname:'groundnut',
        country:'cameroon',
        price:'$720,800',
        origin:'warri',
        specification:'improved quality',
        description:'two tonnes',
        status:'unavailable',
        view:'view',
        delete:'delete',
    },
    {
        id: 6,
        commodityname:'Iron ore',
        country:'Garbon',
        price:'$820,800',
        origin:'Delta',
        specification:'Improved quality',
        description:'full tonne',
        status:'unavailable',
        view:'view',
        delete:'delete',
    },
    {
        id: 7,
        commodityname:'Wood',
        country:'South Africa',
        price:'$320,800',
        origin:'Delta',
        specification:'Improved quality',
        description:'full tonne',
        status:'available',
        view:'view',
        delete:'delete',
    },
    {
        id:8,
        commodityname:'Peanuts',
        country:'Niger',
        price:'$920,800',
        origin:'Mali',
        specification:'Improved',
        description:'3 tonnes',
        status:'availale',
        view:'view',
        delete:'delete',
    },
    {
        id:9,
        commodityname:'Cashew',
        country:'Algeria',
        price:'$550,800',
        origin:'Morocco',
        specification:'Improved',
        description:'4Tonnes',
        status:'soldout',
        view:'view',
        delete:'delete',
    },
    {
        id:10,
        commodityname:'Maize',
        country:'Algeria',
        price:'$650,000',
        origin:'Togo',
        specification:'High Quality',
        description:'4tonnes',
        status:'unavailable',
        view:'view',
        delete:'delete',
    },
    {
        id:11,
        commodityname:'rice',
        country:'Nigeria',
        price:'$750,000',
        origin:'Togo',
        specification:'african grown',
        description:'high',
        status:'availble',
        view:'view',
        delete:'delete',
    },
    {
        id:12,
        commodityname:'cahsew',
        country:'Morocco',
        price:'$77,999',
        origin:'Jigawa',
        specification:'high',
        description:'high',
        status:'soldout',
        view:'view',
        delete:'delete',
    },
    {
        id:13,
        commodityname:'Iron ore',
        country:'Senegal',
        price:'$65,880',
        origin:'Mali',
        specification:'high',
        description:'high',
        status:'available',
        view:'view',
        delete:'delete',
    },
]