export const applicantDatatabless = [
    {
        id: 1,
        fullName:'Peter Obi',
        country:'edinburgh',
        phoneNumber:'$320,800',
        productTraded:'groundnut',
        email:'improved quality',
        age:'30',
        view:'view',
        delete:'delete',
        },
        {
            id: 2,
            fullName:'Atiku Abubakar',
            country:'london',
            phoneNumber:'08099233434',
            productTraded:'garri',
            email:'atiku@gmail.com',
            age:'20',
            view:'view',
            delete:'delete',
            },
    {
        id: 3,
        fullName:'Tinubu Emilokan',
        country:'mali',
        phoneNumber:'0812449384',
        productTraded:'mango',
        email:'tinubu@gmail.com',
        age:'300',
        view:'view',
        delete:'delete',
    },
    {
        id: 4,
        fullName:'Bola Ahmed',
        country:'togo',
        phoneNumber:'0812454684',
        productTraded:'wood',
        email:'bola@gmail.com',
        age:'400',
        view:'view',
        delete:'delete',
    },
    {
        id: 5,
        fullName:'Bola Ahmed',
        country:'togo',
        phoneNumber:'0812454684',
        productTraded:'wood',
        email:'bola@gmail.com',
        age:'400',
        view:'view',
        delete:'delete',
    },
    {
        id: 6,
        fullName:'damilola ani',
        country:'cameroon',
        phoneNumber:'0814893402',
        productTraded:'paddy rice',
        email:'dami@gmail.com',
        age:'500',
        view:'view',
        delete:'delete',
    },
    {
        id: 7,
        fullName:'jennifer aku',
        country:'Niger',
        phoneNumber:'08189923442',
        productTraded:'soya bean',
        email:'jennifer@gmail.com',
        age:'10',
        view:'view',
        delete:'delete',
    },
    {
        id:8,
        fullName:'Rachael Ezeanya',
        country:'Nigeria',
        phoneNumber:'08189923442',
        productTraded:'cocain',
        email:'rachaelr@gmail.com',
        age:'10',
        view:'view',
        delete:'delete',
    },
    {
        id:9,
        fullName:'Victor Lastborn',
        country:'Congo',
        phoneNumber:'08189923442',
        productTraded:'weed',
        email:'victor@gmail.com',
        age:'10',
        view:'view',
        delete:'delete',
    },
    {
        id:10,
        fullName:'Abbey Erhun',
        country:'Ghana',
        phoneNumber:'08189923442',
        productTraded:'yam floor',
        email:'abbe@gmail.com',
        age:'30',
        view:'view',
        delete:'delete',
    },
    
]